config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index", as: :root
  resources :menus
  resources :menuitems
  resources :customers
  resources :orders
  resources :orderitems
  resources :contacts
  resources :randomnumbers
  resources :payments
  get "/aboutus", to: "home#aboutus", as: :about_us
  get "/privacypolicy", to: "home#privacypolicy", as: :privacy_policy
  get "/viewprofile", to: "customers#viewprofile", as: :view_profile_customer
  post "/profile", to: "customers#profile", as: :profile_customer
  get "/forgotpassword", to: "customers#forgotpassword", as: :forgot_password
  get "/checkdetails", to: "customers#checkdetails", as: :check_details
  get "/updatepassword", to: "customers#updatepassword", as: :update_password
  get "/invoice", to: "orders#invoice", as: :invoice
  get "/listorders", to: "orders#listorders", as: :list_orders
  get "/showlist", to: "orders#listshow", as: :show_list_orders
  get "/myorders", to: "orders#myorders", as: :my_orders
  get "/deliver", to: "orders#deliver", as: :deliver_order
  get "/ownermenus", to: "menus#ownermenus", as: :owner_menus
  get "/managemenus", to: "menus#managemenus", as: :manage_menus
  post "/uniquecustomers", to: "customers#uniquecustomer", as: :unique_customer
  get "/listmenuitems", to: "menuitems#listmenuitems", as: :list_menuitems
  get "/showmenuitems", to: "menuitems#menuitemshow", as: :show_menuitems_orders
  post "/menuitem/unique", to: "menuitems#uniquemenuitem", as: :unique_menuitem
  get "/deleteorder", to: "orders#deleteorder", as: :delete_order
  get "/deleteorderitems", to: "orderitems#destroyorderitem", as: :delete_orderitem
  get "/randomnumbers", to: "randomnumbers#index", as: :randomnumbers_path
  get "/createmenuitem", to: "menuitems#createmenuitem", as: :create_menuitem
  get "/destroymenuitem", to: "menuitems#destroymenuitem", as: :destroy_menuitem
  get "/menuitem/unique", to: "menus#index"
  get "/feedback_list", to: "contacts#feedback", as: :feedback_contact
  get "/create", to: "orderitems#create", as: :create_orderitem
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, presence: true
  validates :email, presence: true
  validates :contact_number, presence: true, numericality: { only_integer: true }, length: { minimum: 10 }
  validates :password, length: { minimum: 4, maximum: 9 }, on: :create
  has_secure_password
  has_many :orders
  has_many :randomnumbers

  def notcustomer?
    role != "Customer"
  end

  def self.clerk
    all.where("role=?", "Clerk")
  end

  def self.customer
    all.where("role=?", "Customer")
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    unless current_user.notcustomer?
      flash[:alert] = "You are not accessed to this page"
      redirect_to menus_path
    else
      render "index"
    end
  end

  def new
    render "customers/new"
  end

  def uniquecustomer
    email = params[:email]
    customer = Customer.find_by("email=?", email)
    if customer
      redirect_to customer_path(:id => customer.id)
    else
      flash[:error] = "User with entered details doesn't exist.Please enter valid mail-id again"
      redirect_to customers_path
    end
  end

  def show
    if current_user.role != "Owner"
      flash[:alert] = "You are not accessed for this page!"
      redirect_to menus_path
    else
      @id = params[:id]
    end
  end

  def create
    customer = Customer.find_by(email: params[:email])
    if customer
      flash[:error] = "User with entered details exists.Please try again."
      redirect_to new_customer_path
    else
      new_customer = Customer.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        contact_number: params[:contact_number],
        email: params[:email],
        password: params[:password],
      )
      if Customer.count == 0
        new_customer.role = "Owner"
      else
        new_customer.role = "Customer"
      end
      if new_customer.save
        session[:current_user_id] = new_customer.id
        flash[:alert] = "Welcome to Cafeteria Management.Your account created successfully"
        UserMailer.registration_confirmation(new_customer).deliver
        redirect_to "/"
      else
        flash[:error_signup] = new_customer.errors.full_messages.join(",")
        redirect_to new_customer_path
      end
    end
  end

  def viewprofile
    @user = current_user
  end

  def profile
    id = params[:id]
    email = params[:email]
    customer = Customer.find(id)
    customer_a = Customer.find_by("email=?", email)
    if customer_a == current_user
      customer.first_name = params[:first_name]
      customer.last_name = params[:last_name]
      customer.email = params[:email]
      customer.contact_number = params[:contact_number]
      if customer.save
        flash[:alert] = "Your Profile updated successfully"
        redirect_to menus_path
      else
        flash[:error] = customer.errors.full_messages.join(",")
        redirect_to view_profile_customer_path
      end
    elsif customer_a
      flash[:error] = "User with entered email exists.Please try again."
      redirect_to view_profile_customer_path
    else
      customer.first_name = params[:first_name]
      customer.last_name = params[:last_name]
      customer.email = params[:email]
      customer.contact_number = params[:contact_number]
      if customer.save
        flash[:alert] = "Your Profile updated successfully"
        redirect_to menus_path
      else
        flash[:error] = customer.errors.full_messages.join(",")
        redirect_to view_profile_customer_path
      end
    end
  end

  def update
    id = params[:id]
    customer = Customer.find(id)
    customer.role = params[:role]
    if customer.save
      flash[:alert] = "#{customer.first_name} role changed to #{customer.role} successfully"
    else
      flash[:error] = customer.errors.full_messages.join(",")
    end
    redirect_to customers_path
  end

  def forgotpassword
    render "forgotpassword"
  end

  def checkdetails
    email = params[:email]
    contact_number = params[:contact_number]
    if email != "" and contact_number != "" and contact_number.to_i.to_s == contact_number
      customer = Customer.find_by("email=?", email)
      if customer and customer.contact_number == contact_number.to_i
        redirect_to randomnumbers_path(
          :customer_id => customer.id,
        )
      else
        flash[:error] = "User with entered details not found"
        redirect_to sessions_path
      end
    else
      flash[:error_fill] = "Please fill out details to change password"
      render "forgotpassword"
    end
  end

  def updatepassword
    customer = Customer.find(params[:id])
    otp = params[:otp].to_i
    set_password = params[:set_password]
    confirm_password = params[:confirm_password]
    if otp == Randomnumber.current_user(customer).last.otp
      if set_password == confirm_password
        if set_password.length >= 4 and set_password.length <= 9
          customer.password = set_password
          if customer.save
            flash[:alert] = "Password changed successfully ...."
            redirect_to sessions_path
          else
            flash[:error] = customer.errors.full_messages.join(",")
            redirect_to update_password_path
          end
        else
          flash[:error] = "Invalid Password length. Password should be in between 4 to 9"
          @customer = customer
          render "updatepassword"
        end
      else
        flash[:error] = "Passwords doesnot match.Please try again"
        @customer = customer
        render "updatepassword"
      end
    else
      flash[:error] = "Please enter valid OTP. OTP didn't match"
      @customer = customer
      render "updatepassword"
    end
  end
end

app/views/customers/_customer-section.html.erb
<section class="display_users_section">
  <p class="user_title"> <%= user_title %> </p>
    <% customers.all.each do |customer| %>
      <tr>
          <td class="customer_name">
            <%= customer.first_name.concat(" ").concat(customer.last_name) %>
          </td>
          <td class="customer_email">
            <%= customer.email %>
          </td>
          <td>
            <%= form_with(url: "/customers/#{customer.id}",method: "put", local: true) do %>
              <input type="hidden" name="role" value="<%= cust_value %>">
              <input class="billing_button" type="submit" onclick="return Changerole();" value="<%= button_value %>" data-disable-with="changing...">
            <% end %>
          </td>
      </tr>
    <% end %>
</section>

app/views/customers/forgotpassword.html.erb
<div class="main_content logged_in_background">
  <p class="flash-error-forgot"><%= flash[:error_fill] %></p>
  <p class="title_of_page"> User Details </p>
  <div class="forgot_password_block">
    <%= form_with(url: check_details_path,method: "get",local:true ) do %>
      <input type="text" class="mail_block" name="email" placeholder="Enter Email -id ...">
      <input type="text"
        class="contact_block"
        name="contact_number"
        autocomplete="contact-number"
        maxlength="10"
        placeholder="Contact Number ...">
      <input type="submit" class="confirm_btn" value="Confirm Details">
    <% end %>
  </div>
</div>

app/views/customers/index.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Manage Billing Person </p>
  <%= form_with(url:unique_customer_path,local:true) do %>
    <div class="email_search">
      <div class="input-icons">
        <i class="fa fa-envelope icon_mail"></i>
        <%= text_field_tag(
          name="email",
          value=nil,
          class: "email_input",
          placeholder: "Enter Valid Email-id"
          )
        %>
      </div>
      <button type="submit" class="Form-search search_email_block" data-disable-with="Searching...">
        <i class="fa fa-search"></i>&nbsp;&nbsp;&nbsp;Search
      </button>
    </div>
  <% end %>
  <section class="users_display_page">
    <table class="display_users_to_owner">
      <%= render partial:"customer-section",locals:{
        user_title: "Clerk",
        customers: Customer.clerk,
        cust_value: "Customer",
        button_value: "Remove as Clerk"
        } %>
    </table>
    <table class="display_users_to_owner">
      <%= render partial:"customer-section",locals:{
        user_title: "Customer",
        customers: Customer.customer,
        cust_value: "Clerk",
        button_value: "Mark as Clerk"
        } %>
    </table>
  </section>
</div>

app/views/customers/new.html.erb
<div class="main_content">
  <section class="background_style_signup">
    <div class="Customer_signup">
      <p class="Flash-error-signin_up"> <%= flash[:error_signup] %> </p>
      <section class="NewCustomers">
        <h1 class="NewCustomers_title">Welcome new Customer!</h1>
          <%= form_with url:customers_path do |form| %>
            <div class="Form-section">
              <div class="Form-input-label">First Name:<p class="Mandatory"> * </p></div>
              <div class="input-icons">
                <i class="fa fa-user icon"></i>
                <%= form.text_field :first_name,class:"Form-input",placeholder:"First Name",autofocus: "autofocus" %>
              </div>
            </div>
            <div class="Form-section">
              <div class="Form-input-label">Last Name:</div>
              <%= form.text_field :last_name,class:"Form-input",placeholder:"Last Name" %>
            </div>
            <div class="Form-section">
              <div class="Form-input-label">Contact Number:<p class="Mandatory"> * </p></div>
              <div class="input-icons">
                <i class="fa fa-phone icon"></i>
                <%= form.text_field :contact_number,class:"Form-input",placeholder:"Contact Number" %>
              </div>
            </div>
            <div class="Form-section">
              <div class="Form-input-label">Email:<p class="Mandatory"> * </p></div>
              <div class="input-icons">
                <i class="fa fa-envelope icon"></i>
                <%= form.email_field :email,class:"Form-input",placeholder:"Email-id" %>
              </div>
            </div>
            <div class="Form-section">
              <div class="Form-input-label">Password:<p class="Mandatory"> * </p></div>
              <div class="input-icons">
                <i class="fa fa-key icon"></i>
                <%= form.password_field :password,class:"Form-input",placeholder:"Password" %>
              </div>
            </div>
            <div class="Form-section">
              <%= form.submit "Sign Up",class:"Form-submit",data: { disable_with: "Creating..." } %>
            </div>
          <% end %>
        <p class="Signin_link"> Have an account ? <%= link_to "Sign-in",new_sessions_path,class:"links" %>here </p>
      </section>
    </div>
  </section>
</div>

app/views/customers/show.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Manage Billing Person </p>
  <% customer=Customer.find(@id) %>
  <% if customer.role=="Clerk" %>
    <% cust_value="Customer" %>
    <% button_value="Remove as Clerk" %>
  <% elsif customer.role=="Customer" %>
    <% cust_value="Clerk" %>
    <% button_value="Mark as Clerk" %>
  <% end %>
  <section class="users_billing_section">
    <div class="customer_name">
      <%= customer.first_name.concat(" ").concat(customer.last_name) %>
    </div>
    <div class="customer_email">
      <%= customer.email %>
    </div>
    <%= form_with(url: "/customers/#{customer.id}",method: "put", local: true) do %>
      <div>
        <input type="hidden" name="role" value="<%= cust_value %>">
        <input class="billing_button" type="submit" onclick="return Changerole();" value="<%= button_value %>" data-disable-with="changing...">
      </div>
    <% end %>
  </section>
</div>

app/views/customers/updatepassword.html.erb
<div class="main_content logged_in_background">
  <p class="flash-error-changepassword"><%= flash[:error] %></p>
  <p class="title_of_page"> Change Password </p>
  <div class="update_password_block">
    <%= form_with(url: update_password_path, method: "get", local:true) do %>
      <input type="hidden" name="id" value="<%= @customer.id %>">
      <input type="text" class="password_block" name="otp" placeholder="Enter OTP ....">
      <input type="password" class="password_block" name="set_password" placeholder="Set Password ....">
      <input type="password" class="password_block" name="confirm_password" placeholder="Confirm Password ....">
      <input type="submit" class="change_btn" value="Change Password" onclick="return changepassword();">
    <% end %>
  </div>
</div>

app/views/customers/viewprofile.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Manage Profile </p>
  <section class="viewprofile_block">
    <%= form_with url:profile_customer_path do |form| %>
      <input type="hidden" name="id" value="<%= @user.id %>">
      <div class="Form-section profile-section">
        <div class="Form-input-label profile_label">First Name :</div>
        <div class="input-icons">
          <i class="fa fa-user icon"></i>
          <%= form.text_field :first_name,value:"#{@user.first_name}",class:"Form-input profile-input",placeholder:"First Name",autofocus: "autofocus" %>
        </div>
      </div>
      <div class="Form-section profile-section">
        <div class="Form-input-label profile_label">Last Name :</div>
        <div class="input-icons">
          <%= form.text_field :last_name,value:"#{@user.last_name}",class:"Form-input profile-input",placeholder:"Last Name" %>
        </div>
      </div>
      <div class="Form-section profile-section">
        <div class="Form-input-label profile_label">Contact Number :</div>
        <div class="input-icons">
          <i class="fa fa-phone icon"></i>
          <%= form.text_field :contact_number,value:"#{@user.contact_number}",class:"Form-input profile-input",placeholder:"Contact Number" %>
        </div>
      </div>
      <div class="Form-section profile-section">
        <div class="Form-input-label profile_label">Email :</div>
        <div class="input-icons">
          <i class="fa fa-envelope icon"></i>
          <%= form.email_field :email,value:"#{@user.email}",class:"Form-input profile-input",placeholder:"Email-id" %>
        </div>
      </div>
      <%= form.submit "Update Profile",onclick:"return updateprofile();",class:"update_profile",local:true, data:{disable_with: "Updating ..." }%>
    <% end %>
  </section>
</div>