config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index", as: :root
  resources :menus
  resources :menuitems
  resources :customers
  resources :orders
  resources :orderitems
  resources :contacts
  resources :randomnumbers
  resources :payments
  get "/aboutus", to: "home#aboutus", as: :about_us
  get "/privacypolicy", to: "home#privacypolicy", as: :privacy_policy
  get "/viewprofile", to: "customers#viewprofile", as: :view_profile_customer
  post "/profile", to: "customers#profile", as: :profile_customer
  get "/forgotpassword", to: "customers#forgotpassword", as: :forgot_password
  get "/checkdetails", to: "customers#checkdetails", as: :check_details
  get "/updatepassword", to: "customers#updatepassword", as: :update_password
  get "/invoice", to: "orders#invoice", as: :invoice
  get "/listorders", to: "orders#listorders", as: :list_orders
  get "/showlist", to: "orders#listshow", as: :show_list_orders
  get "/myorders", to: "orders#myorders", as: :my_orders
  get "/deliver", to: "orders#deliver", as: :deliver_order
  get "/ownermenus", to: "menus#ownermenus", as: :owner_menus
  get "/managemenus", to: "menus#managemenus", as: :manage_menus
  post "/uniquecustomers", to: "customers#uniquecustomer", as: :unique_customer
  get "/listmenuitems", to: "menuitems#listmenuitems", as: :list_menuitems
  get "/showmenuitems", to: "menuitems#menuitemshow", as: :show_menuitems_orders
  post "/menuitem/unique", to: "menuitems#uniquemenuitem", as: :unique_menuitem
  get "/deleteorder", to: "orders#deleteorder", as: :delete_order
  get "/deleteorderitems", to: "orderitems#destroyorderitem", as: :delete_orderitem
  get "/randomnumbers", to: "randomnumbers#index", as: :randomnumbers_path
  get "/createmenuitem", to: "menuitems#createmenuitem", as: :create_menuitem
  get "/destroymenuitem", to: "menuitems#destroymenuitem", as: :destroy_menuitem
  get "/menuitem/unique", to: "menus#index"
  get "/feedback_list", to: "contacts#feedback", as: :feedback_contact
  get "/create", to: "orderitems#create", as: :create_orderitem
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :orderitems
  has_one :payments
  validates :address, presence: true, on: :update, length: { minimum: 10 }

  def self.incart
    all.where("status=?", "incart")
  end

  def self.ordered
    all.where("status=?", "ordered")
  end

  def self.cancelled
    all.where("status=?", "cancelled")
  end

  def self.delivered
    all.where("status=?", "delivered")
  end

  def self.fromto(initial_date, final_date)
    all.where("date>=? and date<=?", initial_date, final_date)
  end

  def self.currentuser(user)
    all.where("customer_id=?", user.id)
  end

  def self.notincart
    all.where("status!=?", "incart")
  end

  def self.customername(cust_name)
    all.where("UPPER(REGEXP_REPLACE(customer_name, '\s', '', 'g')) like ?", "%#{cust_name}%")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    unless current_user.notcustomer?
      flash[:alert] = "You are not accessed to this page"
      redirect_to menus_path
    else
      @orders = Order.ordered
    end
  end

  def create
    @orders = Order.incart
    @no_of_items = params[:no_of_items]
    if @orders.currentuser(current_user).count == 0
      order = Order.new(
        date: Date.today,
        customer_id: current_user.id,
        status: "incart",
      )
      if order.save
        @menuitem_id = params[:id]
        @order_id = order.id
        redirect_to create_orderitem_path(
          :order_id => @order_id,
          :menuitem_id => @menuitem_id,
          :no_of_items => @no_of_items,
        )
      else
        flash[:error] = order.errors.full_messages.join(",")
        redirect_to menus_path
      end
    else
      order = @orders.currentuser(current_user).first
      @menuitem_id = params[:id]
      @order_id = order.id
      redirect_to create_orderitem_path(
        :order_id => @order_id,
        :menuitem_id => @menuitem_id,
        :no_of_items => @no_of_items,
      )
    end
  end

  def show
    @orderid = params[:id]
  end

  def invoice
    @orderid = params[:id]
  end

  def myorders
    @orders = Order.currentuser(current_user)
    render "myorders"
  end

  def listshow
    if current_user.role == "Customer"
      flash[:alert] = "You are not accessed to this page"
      redirect_to menus_path
    else
      initial_date = params[:initial_date]
      final_date = params[:final_date]
      cust_name = params[:cust_name].gsub(/\s+/, "").strip.upcase
      if initial_date == "" or final_date == ""
        flash[:alert] = "Please Enter valid dates.Dates can't be empty"
        redirect_to list_orders_path
      elsif initial_date.to_s > final_date.to_s
        flash[:alert] = "Invalid search of dates. From Date is greater than To Date"
        redirect_to list_orders_path
      else
        @orders = Order.fromto(initial_date, final_date)
        if cust_name == "ALL"
          @orders = @orders
        else
          @orders = @orders.customername(cust_name)
        end
        @initial_date = initial_date
        @final_date = final_date
        @customer_name = cust_name
        render "listorders"
      end
    end
  end

  def deliver
    if current_user.role == "Customer"
      flash[:alert] = "You are not accessed to this page"
      redirect_to menus_path
    else
      id = params[:id]
      order = Order.find(id)
      order.date = Date.today
      order.status = "delivered"
      if order.save
        if order.customer_name != "Walk-in-customer"
          UserMailer.order_delivered(order.id).deliver
        end
        flash[:alert] = "Order delivered successfully"
        redirect_to orders_path
      else
        flash[:error] = order.errors.full_messages.join(",")
        redirect_to orderitems_path
      end
    end
  end

  def update
    id = params[:id]
    order = Order.find(id)
    order.bill = params[:bill]
    order.address = params[:address]
    if current_user.role == "Customer"
      order.customer_name = current_user.first_name
    else
      order.customer_name = params[:customer_name]
      if params[:customer_name] == "Walk-in-customer"
        order.date = Date.today
        order.status = params[:status]
      end
    end
    if order.save
      if current_user.role == "Customer"
        redirect_to payments_path(
          :orderid => order.id,
        )
      elsif order.customer_name == "Walk-in-customer"
        flash[:alert] = "Your order confirmed"
        redirect_to menus_path
      else
        redirect_to payments_path(
          :orderid => order.id,
        )
      end
    else
      flash[:error] = order.errors.full_messages.join(",")
      redirect_to orderitems_path
    end
  end

  def listorders
    if current_user.role != "Owner"
      flash[:alert] = "You are not accessed to this page"
      redirect_to menus_path
    else
      initial_date = Date.today - 30
      final_date = Date.today
      @orders = Order.fromto(initial_date, final_date)
      @initial_date = initial_date
      @final_date = final_date
      @customer_name = "ALL"
      render "listorders"
    end
  end

  def destroy
    id = params[:id]
    order = Order.find(id)
    if order.customer_id == current_user.id or current_user.role != "Customer"
      order.date = Date.today
      order.status = "cancelled"
      if order.save
        if order.customer_name != "Walk-in-customer"
          UserMailer.order_cancelled(order.id).deliver
        end
        flash[:alert] = "Order Cancelled Successfully"
      else
        flash[:error] = order.errors.full_messages.join(",")
      end
      if order.customer_id == current_user.id
        redirect_to my_orders_path
      else
        redirect_to orders_path
      end
    else
      flash[:error] = "You are not accessible to this page"
      redirect_to orders_path
    end
  end

  def deleteorder
    id = params[:id]
    order = Order.find(id)
    order.destroy
    redirect_to orderitems_path
  end
end

app/views/orders/_myorder-section.html.erb
<% if count!=0 %>
  <p class="order_items_caption <%= style_class %>"> <%= order_title %> </p>
<table class="list_orders_to_admin">
  <tr class="list_row">
    <th colspan="2" class="heading_lists"> Name </th>
    <th class="heading_lists">Ordered Date</th>
    <th class="heading_lists"> Sub Total</th>
    <th class="heading_lists"> Display Details </th>
    <% if order_title=="Ordered" %>
      <th class="heading_lists"> Cancellation </th>
    <% end %>
  </tr>
  <% value_decides_class=0 %>
  <% orders.notincart.order(:date).each do |order| %>
    <% value_decides_class+=1 %>
    <tr class="<%= value_decides_class.even? ? "list_row_one" : "list_row_two" %>">
    <% customer=Customer.find(order.customer_id) %>
      <td colspan="2" class="list_row_data">
        <%= order.customer_name %>
      </td>
      <td class="list_row_data">
        <%= order.date.to_s(:long) %>
      </td>
      <td class="list_row_data">
        <p class="order_bill"><%= order.bill %>/-</p>
      </td>
      <td class="list_row_data">
        <% if order_title!="Delivered" %>
          <%= form_with(url: "/orders/#{order.id}", method: "get",local: true) do %>
            <input class="button show list_row_show" type="submit" value="Show Details">
          <% end %>
        <% else %>
          <%= form_with(url: invoice_path, method: "get",local: true) do %>
            <input type="hidden" name="id" value="<%= order.id %>">
            <input class="button show list_row_show" type="submit" value="View Invoice">
          <% end %>
        <% end %>
      </td>
      <% if order_title=="Ordered" %>
        <td class="list_row_data">
          <%=  form_with(url: "/orders/#{order.id}",method: "delete",local: true) do %>
              <input type="hidden" name="id" value="<%= order.id %>">
              <input type="submit" value="Cancel order" class="cancel_order" onclick="return myConfirm();">
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>

app/views/orders/_show-orderslist.html.erb
<% total_earning=0 %>
<% orders_list.all.each do |order| %>
  <% total_earning=total_earning+order.bill %>
<% end %>
<p class="totalearning">Total Earning :<%= total_earning %>/-</p>
<table class="list_orders_to_admin">
  <tr class="list_row">
    <th colspan="2" class="heading_lists"> Name </th>
    <th class="heading_lists">
      <% if show_delivered_button %>
        Ordered Date
      <% else %>
        Delivered Date
      <% end %>
    </th>
    <th class="heading_lists"> Contact Number </th>
    <th class="heading_lists"> Sub Total </th>
    <th class="heading_lists"> Details </th>
    <th colspan="2" class="heading_lists"> Address </th>
    <% if show_delivered_button %>
      <th class="heading_lists"> Status </th>
    <% end %>
  </tr>
  <% value_decides_class=0 %>
  <% orders_list.order(:date).each do |order| %>
    <% value_decides_class+=1 %>
    <tr class="<%= value_decides_class.even? ? "list_row_one" : "list_row_two" %>">
    <% customer=Customer.find(order.customer_id) %>
      <td colspan="2" class="list_row_data">
        <%= order.customer_name %>
      </td>
      <td class="list_row_data">
        <%= order.date.to_s(:long) %>
      </td>
      <td class="list_row_data">
        <% if order.customer_name != "Walk-in-customer" %>
          <%= customer.contact_number %>
        <% else %>
          <% number = "- - -" %>
          <%= number %>
        <% end %>
      </td>
      <td class="list_row_data">
        <p class="order_bill"> Bill : <%= order.bill %>/-</p>
      </td>
      <td class="list_row_data">
       <% if show_delivered_button %>
          <%= form_with(url: "/orders/#{order.id}", method: "get",local: true) do %>
            <input class="button show list_row_show" type="submit" value="Show Details">
          <% end %>
        <% else %>
          <%= form_with(url: invoice_path, method: "get",local: true) do %>
            <input type="hidden" name="id" value="<%= order.id %>">
            <input class="button show list_row_show" type="submit" value="View Invoice">
          <% end %>
        <% end %>
      </td>
      <td colspan="2" class="list_row_data">
        <%= order.address %>
      </td>
      <% if show_delivered_button %>
        <td class="list_row_data">
          <%= form_with(url: deliver_order_path, method: "get",local: true) do %>
            <input type="hidden" name="id" value="<%= order.id %>">
            <input class="button delivered" type="submit" onclick="return deliver();" value="Deliver Order">
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/orders/index.html.erb
<div class="main_content logged_in_background">
  <div class="pending_block">
    <p class="title_of_page"> Pending Orders </p>
    <% if @orders.count == 0 %>
      <div class="emptycart_block">
        <img src="pendingorders.png" class="empty-cart-theme">
        <p class="myorders_message message_myorders">No pending orders</p>
        <p class="myorders_message">Wait till someone orders</p>
      </div>
    <% else %>
      <%= render partial:"show-orderslist",locals: {
          orders_list: @orders,
          show_delivered_button:true
        }
      %>
    <% end %>
  </div>
</div>

app/views/orders/invoice.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Invoice Details </p>
  <br>
  <div class="invoice_bill">
    <div class="invoice_block">
      <% order=Order.find(@orderid) %>
      <% customer=Customer.find(order.customer_id) %>
      <div class="invoice_details">
        <div class="bill_from">
          <p class="bill_tags">Bill From:</p>
          <div class="restaurant">
            <div class="restaurant_name"> Restaurant Name:</div>
            <div>Cafeteria (nature's flavor)</div>
          </div>
          <div class="restaurant">
            <p class="invoice_address">Address:</p>
            <div class="address_location">
              <p>16/93,</p>
              <p> Gurujada Road,</p>
              <p> MSR Circle, Chittoor,</p>
              <p>Andhra Pradesh</p>
              <p>517001</p>
            </div>
          </div>
          <div class="restaurant">
            <div class="restaurant_name"> Contact Number:</div>
            <div>9381271441</div>
          </div>
        </div>
        <div class="bill_to">
          <p class="bill_tags">Bill To:</p>
          <div class="restaurant">
            <div class="restaurant_name">Name:</div>
            <div><%= order.customer_name %></div>
          </div>
          <div class="restaurant">
            <div class="restaurant_name">Date:</div>
            <div><%= order.date.to_s(:long) %></div>
          </div>
          <div class="restaurant">
            <div class="restaurant_name">Address:</div>
            <div class="order_address_invoice"><%= order.address %></div>
          </div>
        </div>
      </div>
      <table class="list_invoice">
        <tr class="invoice_row">
          <th class="invoice_lists"> Item name </th>
          <th class="invoice_lists"> Price </th>
          <th class="invoice_lists"> Quantity </th>
          <th class="invoice_lists"> Sub Total </th>
        </tr>
        <% orderitems=order.orderitems %>
        <% orderitems.order(:menuitem_name).each do |orderitem| %>
          <tr class="invoice_row">
            <td class="invoice_row_data">
              <%= orderitem.menuitem_name %>
            </td>
            <td class="invoice_row_data">
              <%= orderitem.menuitem_price %>
            </td>
            <td class="invoice_row_data">
              <%= orderitem.no_of_items %>
            </td>
            <td class="invoice_row_data">
              <%= orderitem.menuitem_price * orderitem.no_of_items %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="invoice_total">Sub Total :&nbsp;<%= order.bill %>&nbsp;/-</p>
    </div>
  </div>
</div>

app/views/orders/listorders.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Sales Based On Dates </p>
  <%= form_with(url: "/showlist", method: "get",local:true) do %>
    <div class="search_records">
      <label class="label_to_records from">
        From Date:
      </label>
        <input class="from_to_button" type="date" name="initial_date">
      <label class="label_to_records to">
        To Date:
      </label>
      <input class="from_to_button" type="date" name="final_date">
       <label class="label_to_records records_name">
        Customer Name:
      </label>
      <input type="text" class="cust_name" name="cust_name" value="All">
      <input class="search_button" type="submit" value="Search" data-disable-with="Searching ...">
    </div>
  <% end %>
  <div class="sales_page">
    <div class="display_dates">From Date :
      <p class="display_ini_fin_dates"><%= @initial_date %></p>
    </div>
    <div class="display_dates">To Date :
      <p class="display_ini_fin_dates"><%= @final_date %></p>
    </div>
    <% if @customer_name !="ALL" %>
      <% if @customer_name!="" %>
        <div class="display_dates">Customer Name :
          <p class="display_ini_fin_dates"><%= @customer_name.capitalize %></p>
        </div>
      <% end %>
    <% end %>
    <% if @orders.delivered.count == 0 %>
      <div class="emptysales_block">
        <img src="nodelivery.jpeg" class="delivery_image">
        <p class="myorders_message message_myorders">
          No sales in respective dates
        </p>
      </div>
    <% else %>
      <%= render partial:"show-orderslist",locals: {
          orders_list:@orders.delivered,
          show_delivered_button:false,
        }
      %>
    <% end %>
  </div>
</div>

app/views/orders/myorders.html.erb
<div class="main_content myorders_background">
  <p class="title_of_page">My Orders</p>
  <% if @orders.notincart.count==0%>
    <div class="emptycart_block">
      <img src="empty-myorders.jpeg" class="empty-myorder-theme">
      <p class="myorders_message">You have not placed any orders yet</p>
      <p class="myorders_message message_myorders">To place an order go back to menu</p>
    </div>
  <% else %>
    <div class="myorders_content">
      <%= render partial:"myorder-section.html.erb", locals: {
        orders: @orders.ordered,
        order_title: "Ordered",
        count: @orders.ordered.count,
        style_class: "order_block"
      }
      %>

      <%= render partial:"myorder-section.html.erb", locals: {
        orders: @orders.cancelled,
        order_title: "Cancelled",
        count: @orders.cancelled.count,
        style_class: "cancel_block"
      }
      %>

      <%= render partial:"myorder-section.html.erb", locals: {
        orders: @orders.delivered,
        order_title: "Delivered",
        count: @orders.delivered.count,
        style_class: "deliver_block"
      }
      %>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Order Details </p>
  <table class="order_table">
    <% bill_value = Order.find(@orderid).bill %>
    <% Orderitem.item_present(@orderid).all.each do |orderitem| %>
      <tr>
        <td>
          <% menu_item=Menuitem.find_by("name=?",orderitem.menuitem_name) %>
          <img src="<%= menu_item.url %>" class="menuitemimage", title="<%= menu_item.name %>" >
        </td>
      </tr>
      <tr class="order_row">
        <td class="order_item_data item_name">
          <p class="myorder_name name_myorders">
            <%= orderitem.menuitem_name %>
          </p>
        </td>
        <td class="order_item_data">
          <div class="myorder_name price_myorders">
            Price :<p class="price_value"><%= orderitem.menuitem_price %></p>/-
          </div>
        </td>
        <td class="order_item_data">
          <p class="myorder_name items_myorders">
            Quantity : <%= orderitem.no_of_items %>
          </p>
        </td>
      </tr>
    <% end %>
  </table>
  <hr width="600px">
  <table class="order_table_bill_line">
      <tr>
        <% order=Order.find(@orderid) %>
        <div class="my_orders_bill_line">
          <td class="order_item_data">
            <p class="Bill <%= order.status=="ordered" ? "in_myorders_cancel" : "in_myorders" %>">Total Bill: <%= order.bill %>/- </p>
          </td>
          <td>
            <% if order.status=="ordered" %>
              <%=  form_with(url: "/orders/#{order.id}",method: "delete",local: true) do %>
                <input type="hidden" name="id" value="<%= order.id %>">
                <input type="submit" value="Cancel order" class="cancel_order" onclick="return myConfirm();">
              <% end %>
            <% end %>
          </td>
        </div>
      </tr>
  </table>
</div>