config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index", as: :root
  resources :menus
  resources :menuitems
  resources :customers
  resources :orders
  resources :orderitems
  resources :contacts
  resources :randomnumbers
  resources :payments
  get "/aboutus", to: "home#aboutus", as: :about_us
  get "/privacypolicy", to: "home#privacypolicy", as: :privacy_policy
  get "/viewprofile", to: "customers#viewprofile", as: :view_profile_customer
  post "/profile", to: "customers#profile", as: :profile_customer
  get "/forgotpassword", to: "customers#forgotpassword", as: :forgot_password
  get "/checkdetails", to: "customers#checkdetails", as: :check_details
  get "/updatepassword", to: "customers#updatepassword", as: :update_password
  get "/invoice", to: "orders#invoice", as: :invoice
  get "/listorders", to: "orders#listorders", as: :list_orders
  get "/showlist", to: "orders#listshow", as: :show_list_orders
  get "/myorders", to: "orders#myorders", as: :my_orders
  get "/deliver", to: "orders#deliver", as: :deliver_order
  get "/ownermenus", to: "menus#ownermenus", as: :owner_menus
  get "/managemenus", to: "menus#managemenus", as: :manage_menus
  post "/uniquecustomers", to: "customers#uniquecustomer", as: :unique_customer
  get "/listmenuitems", to: "menuitems#listmenuitems", as: :list_menuitems
  get "/showmenuitems", to: "menuitems#menuitemshow", as: :show_menuitems_orders
  post "/menuitem/unique", to: "menuitems#uniquemenuitem", as: :unique_menuitem
  get "/deleteorder", to: "orders#deleteorder", as: :delete_order
  get "/deleteorderitems", to: "orderitems#destroyorderitem", as: :delete_orderitem
  get "/randomnumbers", to: "randomnumbers#index", as: :randomnumbers_path
  get "/createmenuitem", to: "menuitems#createmenuitem", as: :create_menuitem
  get "/destroymenuitem", to: "menuitems#destroymenuitem", as: :destroy_menuitem
  get "/menuitem/unique", to: "menus#index"
  get "/feedback_list", to: "contacts#feedback", as: :feedback_contact
  get "/create", to: "orderitems#create", as: :create_orderitem
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  validates :cardnumber, presence: true, numericality: { only_integer: true }, length: { is: 16 }
  validates :cardexpiry, presence: true
  validates :cardholder, presence: true, length: { in: 4..20 }
  validates :cvv, presence: true, length: { is: 3 }
  belongs_to :order
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    if !current_user
      @orderid = params[:orderid]
    else
      @orderid = params[:orderid]
    end
  end

  def create
    cvv = params[:cvv]
    if cvv.to_i.to_s == cvv
      if params[:cardexpiry] != "" and Date.parse(params[:cardexpiry]) >= Date.today
        new_payment = Payment.new(
          order_id: params[:id],
          cardnumber: params[:cardnumber],
          cardexpiry: params[:cardexpiry],
          cardholder: params[:cardholder],
          cvv: params[:cvv],
        )
        if new_payment.save
          order = Order.find(params[:id])
          order.date = Date.today
          order.status = "ordered"
          if order.save
            UserMailer.order_placed(order.id).deliver
            flash[:alert] = "Your order confirmed"
            redirect_to menus_path
          end
        else
          flash[:error_payments] = new_payment.errors.full_messages.join(",")
          redirect_to orderitems_path
        end
      else
        if params[:cardexpiry] == ""
          flash[:error_payments] = "Please enter cardexpiry"
          redirect_to orderitems_path
        else
          flash[:error_payments] = "Your Card expired.Please proceed with valid card"
          redirect_to orderitems_path
        end
      end
    else
      flash[:error_payments] = "Invalid CVV.Please enter valid CVV"
      redirect_to orderitems_path
    end
  end
end

app/views/payments/index.html.erb
<div class="main_content logged_in_background">
  <p class="title_of_page"> Payment page </p>
  <div class="payment_block">
    <%= form_with(url: payments_path,method: "post",local:true) do %>
      <input type="hidden" name="id" value="<%= @orderid %>">
      <div class="card_details">
        <label class="label-heading"> Card Number :</label>
        <input type="text" class="payment-input" name="cardnumber" autocomplete="cardnumber" maxlength="16" placeholder="xxxx xxxx xxxx xxxx">
        <label class="label-heading expiry"> Card Expiry :</label>
        <input type="date" size="5" class="payment-input" name="cardexpiry" placeholder="xx/xx">
      </div>
      <div class="card_details">
        <label class="label-heading-name"> Name on card :</label>
        <input type="text" class="cardholder payment-input" name="cardholder" size="15" placeholder="Cardholder Name">
      </div>
      <div class="card_details">
        <label class="label-heading-cvv"> Security Number(CVV) :</label>
        <input type="text" class="payment-input" name="cvv" size="5" autocomplete="cvv" maxlength="3" placeholder="000">
      </div>
      <div class="card_details">
        <input type="submit" class="payment-submit" value="Confirm Payment" data-disable-with="Confirming ...">
      </div>
    <% end %>
  </div>
</div>