config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index", as: :root
  resources :menus
  resources :menuitems
  resources :customers
  resources :orders
  resources :orderitems
  resources :contacts
  resources :randomnumbers
  resources :payments
  get "/aboutus", to: "home#aboutus", as: :about_us
  get "/privacypolicy", to: "home#privacypolicy", as: :privacy_policy
  get "/viewprofile", to: "customers#viewprofile", as: :view_profile_customer
  post "/profile", to: "customers#profile", as: :profile_customer
  get "/forgotpassword", to: "customers#forgotpassword", as: :forgot_password
  get "/checkdetails", to: "customers#checkdetails", as: :check_details
  get "/updatepassword", to: "customers#updatepassword", as: :update_password
  get "/invoice", to: "orders#invoice", as: :invoice
  get "/listorders", to: "orders#listorders", as: :list_orders
  get "/showlist", to: "orders#listshow", as: :show_list_orders
  get "/myorders", to: "orders#myorders", as: :my_orders
  get "/deliver", to: "orders#deliver", as: :deliver_order
  get "/ownermenus", to: "menus#ownermenus", as: :owner_menus
  get "/managemenus", to: "menus#managemenus", as: :manage_menus
  post "/uniquecustomers", to: "customers#uniquecustomer", as: :unique_customer
  get "/listmenuitems", to: "menuitems#listmenuitems", as: :list_menuitems
  get "/showmenuitems", to: "menuitems#menuitemshow", as: :show_menuitems_orders
  post "/menuitem/unique", to: "menuitems#uniquemenuitem", as: :unique_menuitem
  get "/deleteorder", to: "orders#deleteorder", as: :delete_order
  get "/deleteorderitems", to: "orderitems#destroyorderitem", as: :delete_orderitem
  get "/randomnumbers", to: "randomnumbers#index", as: :randomnumbers_path
  get "/createmenuitem", to: "menuitems#createmenuitem", as: :create_menuitem
  get "/destroymenuitem", to: "menuitems#destroymenuitem", as: :destroy_menuitem
  get "/menuitem/unique", to: "menus#index"
  get "/feedback_list", to: "contacts#feedback", as: :feedback_contact
  get "/create", to: "orderitems#create", as: :create_orderitem
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeteria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
      function myConfirm()
      {
        var result=confirm("Want to cancel an order?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }

      function changepassword()
      {
        var result=confirm("Want to change your password?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }

      function Changerole()
      {
        var result=confirm("Want to change role?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }

      function confirmorder()
      {
        var result=confirm("Want to confirm order?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }

      function updateprofile()
      {
        var result=confirm("Want to Update Profile?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }

      function deliver()
      {
        var result=confirm("Want to deliver order?");
        if(result==true)
        {
          return true;
        }
        else{
          return false;
        }
      }
    </script>
  </head>


  <body>
      <% if @current_user %>
        <div class="Customer_heading">
          <div class="dropdown">
            <span><i class="fa fa-bars bars_display" style="font-size:20px"></i></span>
            <div class="dropdown-content">
                <% if @current_user %>
                  <p class="dropdown-lists">
                    <%= link_to "My Orders", my_orders_path, class:"links_dropdown" %>
                  </p>
                <% end %>
                <% if @current_user.role == "Owner" or @current_user.role == "Clerk" %>
                  <p class="dropdown-lists" >
                    <%= link_to "Pending Orders", orders_path, class:"links_dropdown"%>
                  </p>
                <% end %>
                <% if @current_user.role == "Owner" %>
                  <p class="dropdown-lists" >
                    <%= link_to "Sales Based on Dates", list_orders_path, class:"links_dropdown" %>
                  </p>
                  <p class="dropdown-lists" >
                    <%= link_to "Sales Based on Products", list_menuitems_path, class:"links_dropdown" %>
                  </p>
                  <p class="dropdown-lists" >
                    <%= link_to "Manage Menus", manage_menus_path, class:"links_dropdown" %>
                  </p>
                  <p class="dropdown-lists">
                    <%= link_to "Make an Order",owner_menus_path,class:"links_dropdown" %>
                  </p>
                  <p class="dropdown-lists" >
                    <%= link_to "Manage Billing Persons", customers_path, class:"links_dropdown" %>
                  </p>
                <% end %>
            </div>
          </div>
          <%= image_tag "Logo.png",class:"logo" %>
          <div class="welcome">Welcome <%= @current_user.first_name %>!</div>
          <section class="header_section">
            <p class="main_header_links" >
              <%= link_to "Home", menus_path, class:"main_link" %>
            </p>
            <p class="main_header_links" >
              <%= link_to "View Profile", view_profile_customer_path, class:"main_link" %>
            </p>
            <% if @current_user.role!="Customer" %>
              <p class="main_header_links">
                <%= link_to "View Feedback", feedback_contact_path, method:"get", class:"main_link" %>
              </p>
            <% end %>
            <div class="main_header_links">
                <%= form_with(url: "/orderitems", method: "get", local:true) do %>
                  <%= image_submit_tag(
                        source="cart.png",
                        class: "cart_image",
                        title:"cart"
                    )
                  %>
                <% end %>
            </div>
            <p class="main_header_links">
              <%= link_to "Sign out", destroy_session_path, method:"delete", class:"main_link" %>
            </p>
          </section>
        </div>
      <% else %>
        <div class="Home_creation_line">
          <%= image_tag "Logo.png",class: "logo home_page" %>
          <div class="home-header">
            <p class="Home_menu"><%= link_to "Home", root_path,class:"links home_link" %>
            <p class="Home_menu"><%= link_to "About Us", about_us_path,class:"links home_link" %>
            <p class="Home_menu"><%= link_to "Contact Us", contacts_path,class:"links home_link" %>
            <p class="Home_menu" ><%= link_to "Create Account", new_customer_path,class:"links home_link" %></p>
            <p class="Home_menu" ><%= link_to "Sign in",new_sessions_path,class:"links home_link" %></p>
          </div>
      </div>
    <% end %>
    <% if @current_user %>
        <div class="flash_background">
          <p class="Flash-alert"> <%= flash[:alert] %> </p>
          <p class="Flash-error"> <%= flash[:error] %> </p>
          <p class="Flash-alert-message"> <%= flash[:alert_message] %> </p>
        </div>
    <% end %>
    <%= yield %>
    <div class="footer_line">
      <div class="social_media">
        <p class="social_media_header">Follow us on</p>
        <a href="https://www.facebook.com/cafeteria.naturesflavor" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-facebook-square social_media_links" style="font-size:24px"></i>
        </a>
        <a href="https://www.twitter.com/naturesflavor" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-twitter-square social_media_links" style="font-size:24px"></i>
        </a>
        <a href="https://www.instagram.com/cafeteria2222/" target="_blank" rel="noopener noreferrer">
          <i class="fa fa-instagram social_media_links" style="font-size:24px"></i>
        </a>
      </div>
      <div class="home-footer">
        <p class="Home_menu"><%= link_to "Privacy Policy", privacy_policy_path,class:"links home_link" %>
        <p class="Home_menu"><%= link_to "Contact Us", contacts_path,class:"links home_link" %>
        <div class="address">
          <h2 class="address_heading"> Address : </h2>
          <p class="address_content">16/93,</p>
          <p class="address_content"> Gurujada Road,</p>
          <p class="address_content"> MSR Circle, Chittoor,</p>
          <p class="address_content">Andhra Pradesh</p>
          <p class="address_content">517001</p>
          <p class="address_content">9381271441</p>
        </div>
      </div>
    </div>
  </body>
</html>